##
 # MAKEFILE for the program file mvr.c
 #
 # Compile Environment:
 # 		gcc version 4.4.3 (Ubuntu 4.4.3-4ubuntu5.1) 
##

XX = gcc
CFLAGS = -w
TARGETS = mvr

all: $(TARGETS)

mvr: mvr.c
	$(XX) $(CFLAGS) -o $@ $<

clean:
	rm -rf $(TARGETS)
